workflows:
  flutter-ios-workflow:
    name: Flutter iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    # IMPORTANT: This workflow MUST be selected in Codemagic UI
    # Go to Workflow Editor → Select "flutter-ios-workflow" from dropdown
    environment:
      flutter: 3.29.3
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd /Users/builder/clone
          flutter pub get
      - name: Verify code signing configuration
        script: |
          echo "Verifying App Store distribution configuration..."
          echo "Bundle ID: com.freshducky.myrentrange"
          echo "Expected distribution type: app_store"
      - name: Flutter build ipa
        script: |
          cd /Users/builder/clone
          flutter clean
          flutter build ipa --release
    # Code signing configuration - Force App Store distribution
    # CRITICAL: This must be set to app_store for App Store Connect uploads
    # If Codemagic still uses Development profiles, check:
    # 1. App Store Connect API key is properly configured
    # 2. UI settings aren't overriding this YAML config
    # 3. App Store distribution certificate exists in Apple Developer Portal
    ios_signing:
      distribution_type: app_store
      bundle_id: com.freshducky.myrentrange
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - kevon@example.com  # Update with your email
        notify:
          success: true
          failure: false
      slack:
        notify:
          success: true
          failure: true

  flutter-android-workflow:
    name: Flutter Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: 3.29.3
      java: 17
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd /home/builder/clone
          flutter pub get
      - name: Flutter build apk
        script: |
          cd /home/builder/clone
          flutter clean
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - kevon@example.com  # Update with your email
        notify:
          success: true
          failure: false

